import {
  Bold,
  Baseline,
  LoaderCircle,
  Italic,
  Underline,
  Quote,
  Pilcrow,
  TextQuote,
  Strikethrough,
  Minus,
  Eraser,
  PaintRoller,
  Redo2,
  Undo2,
  ChevronUp,
  ChevronDown,
  Subscript,
  Superscript,
  Code,
  Code2,
  Type,
  IndentIncrease,
  IndentDecrease,
  List,
  ListOrdered,
  ListTodo,
  Link,
  ImageUp,
  Video,
  Maximize,
  Minimize,
  Table,
  Sparkles,
  Pencil,
  Unlink,
  BetweenHorizontalEnd,
  BetweenHorizontalStart,
  BetweenVerticalStart,
  BetweenVerticalEnd,
  TableCellsMerge,
  TableCellsSplit,
  Trash2,
  Trash,
  Replace,
  ChevronsUpDown,
  Heading1,
  Heading2,
  Heading3,
  Columns2,
  Columns3,
  Columns4,
  Plus,
  GripVertical,
  Copy,
  Clipboard,
  PanelLeft,
  PanelRight,
  Columns,
  ChevronRight,
  ArrowUp,
  ClipboardPaste,
  Scissors,
  File,
  RefreshCcw,
  Eye,
  Printer,
  Tablet,
  Smartphone,
  Monitor,
  TextSelect,
  SpellCheck2,
  TextSearch,
  X,
  FlipVertical,
  FlipHorizontal,
  WrapText,
  Check,
  Sun,
  Moon,
  Paintbrush,
  ImageUpscale,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Wand2,
  FileText,
  Map,
  Play,
  Palette,
  Workflow,
  FormInput,
  Omega,
  CodeXml,
  AppWindow,
} from 'lucide-vue-next'

import { ExtraIcons } from './ExtraIcons'
// 图标映射 - 直接映射到组件
export const icons = {
  Bold,
  LoaderCircle,
  Italic,
  Underline,
  Quote,
  TextQuote,
  Strikethrough,
  Minus,
  Eraser,
  PaintRoller,
  Redo2,
  Undo2,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ChevronUp,
  ChevronDown,
  Subscript,
  Superscript,
  Code,
  Code2,
  Type,
  IndentIncrease,
  IndentDecrease,
  List,
  ListOrdered,
  ListTodo,
  Link,
  ImageUp,
  Video,
  Maximize,
  Minimize,
  Table,
  Sparkles,
  Magic: Wand2,
  Pencil,
  Unlink,
  BetweenHorizonalEnd: BetweenHorizontalEnd,
  BetweenHorizonalStart: BetweenHorizontalStart,
  ColumnDelete: ExtraIcons.ColumnDelete,
  BetweenVerticalStart,
  BetweenVerticalEnd,
  RowDelete: ExtraIcons.RowDelete,
  TableCellsMerge,
  TableCellsSplit,
  Trash2,
  Trash,
  Replace,
  ChevronsUpDown,
  LineHeight: Baseline,
  Word: ExtraIcons.Word,
  Paragraph: Pilcrow,
  Heading1,
  Heading2,
  Heading3,
  Columns2,
  Columns3,
  Columns4,
  Plus,
  Grip: GripVertical,
  Copy,
  Clipboard,
  MenuDown: ChevronDown,
  SizeS: ExtraIcons.SizeS,
  SizeM: ExtraIcons.SizeM,
  SizeL: ExtraIcons.SizeL,
  PanelLeft,
  PanelRight,
  Columns,
  AI: Sparkles,
  ChevronRight,
  ArrowUp,
  Paste: ClipboardPaste,
  Cut: Scissors,
  File,
  Refresh: RefreshCcw,
  Eye,
  Printer,
  Tablet,
  Phone: Smartphone,
  Monitor,
  TextSelect,
  SpellCheck: SpellCheck2,
  DocSearch: TextSearch,
  Close: X,
  ImageSize: ImageUpscale,
  FlipVertical,
  FlipHorizontal,
  WrapText,
  Check,
  Sun,
  Moon,
  Paintbrush,
  Youku: Play,
  BiliBili: Play,
  Modao: FileText,
  Baidu: ExtraIcons.ColumnDelete,
  Gaode: Map,
  Lanhu: Palette,
  QQVideo: Play,
  Figma: Palette,
  Canva: Palette,
  Processon: Workflow,
  Codepen: Code,
  Jinshuju: FormInput,
  Omega,
  CodeXml,
  Iframe: AppWindow,
} as const

export default icons
